### PR TITLE
fix!: improve detect algorithm, `detect` runs `null` when dismatch, fix #9

### LINKED ISSUE #9: inconsistency on projects with --no-lockfile
This line is resolving PM wrongly as it first assumes that projects contain lockfile

https://github.com/antfu-collective/package-manager-detector/blob/2c335cd32dbacc01e89216e9eda40b13e616b942/src/index.ts#L25

### PR DESCRIPTION
**Pull request by antfu**
Change to scan the lock and package.json at the same time and return the first match. Ideally it would be sightly more efficient as the lookup will only happen once now

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -12,77 +12,96 @@ export interface DetectOptions {
...
 export { AGENTS, LOCKS }
 
-export async function detect({ cwd, onUnknown }: DetectOptions = {}) {
-  let agent: Agent | undefined
-  let version: string | undefined
-
-  const lockPath = await findUp(Object.keys(LOCKS), { cwd })
-  let packageJsonPath: string | undefined
+export interface DetectResult {
+  agent: Agent
```
Comment (benmccann) [inline src/index.ts:22]: a bit unrelated to the issue being solved here, but I though I'd mention that the other thing that might be helpful here is to return the package manager. most usages I've seen are just looking for that and so always end up having to do `agent.split('@')[0]`

File: src/index.ts [hunk 2]
```diff
@@ -12,77 +12,96 @@ export interface DetectOptions {
...
-        else if (AGENTS.includes(name)) {
-          agent = name
-        }
-        else {
-          onUnknown?.(pkg.packageManager)
-        }
+  for (const directory of lookup(cwd)) {
+    // Look up for lock files
+    for (const lock of Object.keys(LOCKS)) {
+      if (await fileExists(path.join(directory, lock))) {
```
Comment (benmccann) [inline src/index.ts:32]: I'm not sure if this would solve the reported issue. I understood the issue to be something like:
```
rootproj
  |-package.json
  |-pnpm.lock
  |-packages
        |- subproj
              |- package.json (contains packageManager field)
```
So I think we'd need to check for the presence of the `packageManager` field independently of checking for the lockfile

Comment (antfu) [reply src/index.ts:32]: Yeah that's the new behaviour. Instead of `findUp` separately for locks and packageManager field, now we check both in each directory up (the `lookup` function) and get the closest match

File: src/index.ts (hunk 1 above)
Comment (antfu) [reply src/index.ts:22]: We can do another PR to separate that fields
